export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';

export const GET_BURGER_FROM_SERVER_SUCCESS = 'GET_BURGER_FROM_SERVER_SUCCESS';
export const GET_BURGER_FROM_SERVER_FAILED = 'GET_BURGER_FROM_SERVER_FAILED';

export const GET_ORDERS_FROM_SERVER = 'GET_ORDERS_FROM_SERVER';
export const GET_ORDERS_FROM_SERVER_START = 'GET_ORDERS_FROM_SERVER_START';
export const GET_ORDERS_FROM_SERVER_SUCCESS = 'GET_ORDERS_FROM_SERVER_SUCCESS';
export const GET_ORDERS_FROM_SERVER_FAILED = 'GET_ORDERS_FROM_SERVER_FAILED';

export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL';
export const PURCHASE_INIT = 'PURCHASE_INIT';

export const AUTH_START = 'AUTH_START';
export const AUTH_START_SUCCESS = 'AUTH_START_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';